services:
  backend:
    build: src/backend
    container_name: contrato-ai-backend
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - PINECONE_HOST=${PINECONE_HOST}
      - PINECONE_INDEX_NAME=${PINECONE_INDEX_NAME}
      - OPENAI_MODEL=${OPENAI_MODEL}
    ports:
      - 8002:8002
    volumes:
      - ./src/backend/:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8002
    restart: unless-stopped

  frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    container_name: contrato-ai-frontend
    ports:
      - 3000:5173
    volumes:
      - ./src/frontend:/app
      - /app/node_modules
    working_dir: /app
    command: npm run dev -- --host 0.0.0.0
    restart: unless-stopped
    depends_on:
      - backend
